// Generated by CoffeeScript 1.9.0
'use strict';
var concat, parseUrl, request;

request = require('http').request;

parseUrl = require('url').parse;

concat = require('concat-stream');

process.stdin.setEncoding('utf8');

process.stdin.pipe(concat(function(rawInput) {
  var data, headers, json, method, options, req, url, _ref;
  _ref = JSON.parse(rawInput), method = _ref.method, url = _ref.url, json = _ref.json, headers = _ref.headers;
  options = parseUrl(url);
  options.method = method;
  options.headers = headers || {};
  options.agent = false;
  if (json) {
    data = new Buffer(JSON.stringify(json));
    options.headers['Content-Type'] = 'application/json';
    options.headers['Content-Length'] = data.length;
  }
  req = request(options);
  req.on('response', function(res) {
    res.setEncoding('utf8');
    return res.pipe(concat(function(body) {
      var result;
      result = JSON.stringify({
        statusCode: res.statusCode,
        headers: res.headers,
        body: body
      }) + '\n';
      return process.stdout.write(result, function() {
        return process.exit(0);
      });
    }));
  });
  if (data) {
    return req.end(data);
  } else {
    return req.end();
  }
}));
